---
title: "Simulation_study"
date: "2023-09-14"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(devtools)
load_all()
```

```{r}
# Set the random seed for reproducibility
set.seed(23)

# Load required libraries
library(ggplot2)
library(tictoc)

# Define a polynomial simulation function with more descriptive parameter names
polynom <- function(x,a,b,c,d,e,f,g,h){
  y <- NULL
  for(i in 1:length(x)){
    y[i] <- sin(a*x[i])+cos(b*x[i]) + c*x[i] + rnorm(1,0,d*exp(e*sin(f*x[i])+g*x[i])+h)
  }
  y_true_mu <- NULL
  for(i in 1:length(x)){
    y_true_mu[i] <- sin(a*x[i])+cos(b*x[i]) + c*x[i]
  }
  y_true_sig <- NULL
  for(i in 1:length(x)){
    y_true_sig[i] <- d*exp(e*sin(f*x[i])+g*x[i])+h
  }
  
  poly <- cbind(y,y_true_mu,y_true_sig,x)
  return(poly)
}

# Define parameters for the polynomial function
parameters <- matrix(c(3,2,2,0.05,1,2,0.4,0.09,
                       1,2,1,0.06,1,2,0.6,0.11,
                       0.6,2,2,0.4,1,2,0.6,0.01,
                       3,2,0.6,0.06,1,2,0.4,0.4,
                       2,3,0.4,0.18,1,2,0.6,0.02,
                       2,0.6,3,0.9,0.4,3,0.12,0.01,
                       2,3,0,0.05,2,1,0.4,0.18,
                       2,3,3,0.06,2,3,0.6,0.12,
                       3,2,2,0.05,1,0.6,0.12,0.09,
                       3,3,2,0.06,2,1,0.4,0.19), nrow = 8)


parameters <- t(parameters)

simulation <- function(n_obs, 
                       sim_min, sim_max,
                       parameters){

  #generate x-data:
  sim_x <- seq(sim_min, sim_max, length.out = n_obs)

  #choose parameter
  Simulated_data <- vector(mode = "list", length = n_sim)

  #build polynomials
  sim_data <- polynom(sim_x, 
                      a = parameters[1],
                      b = parameters[2],
                      c = parameters[3],
                      d = parameters[4],
                      e = parameters[5],
                      f = parameters[6],
                      g = parameters[7],
                      h = parameters[8])
    Simulated_data <- as.data.frame(sim_data)

  
  return(Simulated_data)

}


########################################################


spline_result <- vector(mode = "list", length = 2)
spline_result[[1]] <- vector(mode = "list", length = 10*5)
spline_result[[2]] <- vector(mode = "list", length = 10*5)

obs <- c(50, 100, 200, 300, 500)
n_sim <- 5
simulationdata <- vector(mode = "list", length = n_sim)

for(k in 1:n_sim){
  simulationdata[[k]] <- spline_result
}



#######################################################
library(tictoc)

tic()
for(k in 1:n_sim){

  for(i in 1:5){
  
    for(j in 1:10){
    
      simulationdata[[k]][[1]][[j +(i-1)*10]] <- simulation(
                  n_obs = obs[i],
                  sim_min = 0,
                  sim_max = 5,
                  parameters = parameters[j,])
    }
  }
}    
toc()
```

```{r}
for(k in 1:n_sim){
  for(i in 1:50){
   simulationdata[[k]][[2]][[i]] <- lmls_bspline(
      vector_x = simulationdata[[k]][[1]][[i]]$x, 
      response_vector_y = simulationdata[[k]][[1]][[i]]$y,
      knot_count = 20,
      poly_degree = 3,
      order_difference_matrix_r = 3,
      max_iterations = 50,
      lambda_mu = 3,
      lambda_sigma = 500,
      opt_method = "GCV",
      lambda_acc = 50
    )
  }
}
toc()
simulationsdata_save <- list(simulationdata = simulationdata,
                             obs = obs,
                             n_sim = n_sim)
saveRDS(simulationsdata_save, file = "results_simulationdata.rds")

```











## Auswertung

```{r}
simulationdata_save <- readRDS("results_simulationdata.rds")
simulationdata <- simulationdata_save$simulationdata
obs <- simulationdata_save$obs
n_sim <- simulationdata_save$n_sim


###

Auswertungsdaten <- vector(mode = "list", length = 50)
for(m in 1:50){
  Auswertungsdaten[[m]] <- vector(mode = "list", length = n_sim) 
}

for(m in 1:10){
  for (k in 1:n_sim) {
    Auswertungsdaten[[m]][[k]] <- matrix(c(rep(0, times = obs[1]*4)), ncol = 4)
    colnames(Auswertungsdaten[[m]][[k]]) <- c("mu", "mu_hat", "sigma", "sigma_hat")
  }
}
for(m in 11:20){
  for (k in 1:n_sim) {
    Auswertungsdaten[[m]][[k]] <- matrix(c(rep(0, times = obs[2]*4)), ncol = 4)
    colnames(Auswertungsdaten[[m]][[k]]) <- c("mu", "mu_hat", "sigma", "sigma_hat")
  }
}
for(m in 21:30){
  for (k in 1:n_sim) {
    Auswertungsdaten[[m]][[k]] <- matrix(c(rep(0, times = obs[3]*4)), ncol = 4)
    colnames(Auswertungsdaten[[m]][[k]]) <- c("mu", "mu_hat", "sigma", "sigma_hat")
  }
}
for(m in 31:40){
  for (k in 1:n_sim) {
    Auswertungsdaten[[m]][[k]] <- matrix(c(rep(0, times = obs[4]*4)), ncol = 4)
    colnames(Auswertungsdaten[[m]][[k]]) <- c("mu", "mu_hat", "sigma", "sigma_hat")
  }
}
for(m in 41:50){
  for (k in 1:n_sim) {
    Auswertungsdaten[[m]][[k]] <- matrix(c(rep(0, times = obs[5]*4)), ncol = 4)
    colnames(Auswertungsdaten[[m]][[k]]) <- c("mu", "mu_hat", "sigma", "sigma_hat")
  }
}





###


for (m in 1:50) {
  for(k in 1:n_sim){
    Auswertungsdaten[[m]][[k]][,1] <- simulationdata[[k]][[1]][[m]]$y_true_mu
  }
}

for (m in 1:50) {
  for(k in 1:n_sim){
    Auswertungsdaten[[m]][[k]][,2] <- simulationdata[[k]][[2]][[m]]$mu_hat
  }
}

for (m in 1:50) {
  for(k in 1:n_sim){
    Auswertungsdaten[[m]][[k]][,3] <- simulationdata[[k]][[1]][[m]]$y_true_sig
  }
}

for (m in 1:50) {
  for(k in 1:n_sim){
    Auswertungsdaten[[m]][[k]][,4] <- simulationdata[[k]][[2]][[m]]$sigma_hat
  }
}


```






## Performance measures
```{r}
bias <- function(theta, theta_hat){
  n_obs <- length(theta)
  theta_bar <- mean(theta)
  bias_result <- 1/n_obs * sum(theta_hat - theta)
  bias_MCSE <- sqrt(1/(n_obs*(n_obs-1))*sum((theta_hat - theta_bar)^2))
  result <- list(bias = bias_result, MCSE = bias_MCSE)
  return(result)
}

emp_sd <- function(theta, theta_hat){
  n_obs <- length(theta)
  theta_bar <- mean(theta)
  sd_result <- sqrt(1/(n_obs-1) * sum((theta_hat - theta_bar)^2))
  sd_MCSE <- sd_result / sqrt(2*(n_obs-1))
  result <- list(emp_sd = sd_result, MCSE = sd_MCSE)
  return(result)
}


MSE <- function(theta, theta_hat){
  n_obs <- length(theta)
  MSE_result <- 1/n_obs * sum((theta_hat - theta)^2)
  MSE_MCSE <- sqrt((sum((theta_hat - theta)^2 - MSE_result)^2) / (n_obs * (n_obs - 1))) 
  result <- list(MSE = MSE_result, MCSE = MSE_MCSE)
  return(result)
}



precision_increase <- function(theta, theta_hat_A, theta_hat_B, n_sim){
  n_obs <- length(theta)
  emp_sd_A <-emp_sd(theta, theta_hat_A)
  emp_sd_A <- emp_sd_A$emp_sd
  emp_sd_B <- emp_sd(theta, theta_hat_B)
  emp_sd_B <- emp_sd_B$emp_sd
  incr_result <- 100 * ((emp_sd_A/emp_sd_B)^2 - 1)
  incr_MCSE <- 200 * (emp_sd_A/emp_sd_B)^2 * sqrt((1- cor(theta_hat_A, theta_hat_B)^2)/(n_obs - 1))
  result <- list(prec_incr = incr_result, MCSE = incr_MCSE)
  return(result)
}
```

## Bias Auswertung
```{r}

bias_results <- vector(mode = "list", length = 50)

for(m in 1:50){
  bias_results[[m]] <- matrix(rep(0, times = n_sim * 2), ncol = 2)
}

for(m in 1:50){
  for(k in 1:n_sim){
    bias_results[[m]][k , 1] <- 
      bias(theta = Auswertungsdaten[[m]][[k]][,1],
           theta_hat = Auswertungsdaten[[m]][[k]][,2])$bias
  }
}

for(m in 1:50){
  for(k in 1:n_sim){
    bias_results[[m]][k , 2] <- 
      bias(theta = Auswertungsdaten[[m]][[k]][,3],
           theta_hat = Auswertungsdaten[[m]][[k]][,4])$bias
  }
}



#averages:

bias_av_result <- matrix(rep(0, 50*2), ncol = 2)
colnames(bias_av_result) <- c("mu", "sigma")

for(m in 1:50){
  bias_av_result[m,1] <- round(mean(bias_results[[m]][,1]),3)
}

for(m in 1:50){
  bias_av_result[m,2] <- round(mean(bias_results[[m]][,2]),3)
}
```


## StDev Auswertung
```{r}
empsd_results <- vector(mode = "list", length = 50)

for(m in 1:50){
  empsd_results[[m]] <- matrix(rep(0, times = n_sim * 2), ncol = 2)
}

for(m in 1:50){
  for(k in 1:n_sim){
    empsd_results[[m]][k , 1] <- 
      emp_sd(theta = Auswertungsdaten[[m]][[k]][,1],
           theta_hat = Auswertungsdaten[[m]][[k]][,2])$emp_sd
  }
}

for(m in 1:50){
  for(k in 1:n_sim){
    empsd_results[[m]][k , 2] <- 
      emp_sd(theta = Auswertungsdaten[[m]][[k]][,3],
           theta_hat = Auswertungsdaten[[m]][[k]][,4])$emp_sd
  }
}


#averages:

empsd_av_result <- matrix(rep(0, 50*2), ncol = 2)
colnames(empsd_av_result) <- c("mu", "sigma")

for(m in 1:50){
  empsd_av_result[m,1] <- round(mean(empsd_results[[m]][,1]),3)
}

for(m in 1:50){
  empsd_av_result[m,2] <- round(mean(empsd_results[[m]][,2]),3)
}
```


## MSE Auswertung
```{r}
MSE_results <- vector(mode = "list", length = 50)

for(m in 1:50){
  MSE_results[[m]] <- matrix(rep(0, times = n_sim * 2), ncol = 2)
}

for(m in 1:50){
  for(k in 1:n_sim){
    MSE_results[[m]][k , 1] <- 
      MSE(theta = Auswertungsdaten[[m]][[k]][,1],
           theta_hat = Auswertungsdaten[[m]][[k]][,2])$MSE
  }
}

for(m in 1:50){
  for(k in 1:n_sim){
    MSE_results[[m]][k , 2] <- 
      MSE(theta = Auswertungsdaten[[m]][[k]][,3],
           theta_hat = Auswertungsdaten[[m]][[k]][,4])$MSE
  }
}


#averages:

MSE_av_result <- matrix(rep(0, 50*2), ncol = 2)
colnames(MSE_av_result) <- c("mu", "sigma")

for(m in 1:50){
  MSE_av_result[m,1] <- round(mean(MSE_results[[m]][,1]),3)
}

for(m in 1:50){
  MSE_av_result[m,2] <- round(mean(MSE_results[[m]][,2]),3)
}
```

# Grafiken

## Grafiken für Bias
```{r}
library(ggplot2)

plotx_<- <- vector(mode = "list", length = 10)

for (f in 1:10){
  plotx_bias[[f]] <- matrix(rep(0, 3*5), ncol = 3)
  colnames(plotx_bias[[f]]) <- c("obs", "mu", "sigma")
}

#obs:
for (e in 1:10) {
  for (i in 1:5){
      plotx_bias[[e]][i,1] <- obs[i]
  }
}


#mean:
for (e in 1:10) {
  for (i in 1:5){
      plotx_bias[[e]][i,2] <- bias_av_result[e +(i-1)*10,1]
  }
}


#sigma:
for (e in 1:10) {
  for (i in 1:5){
      plotx_bias[[e]][i,3] <- bias_av_result[e +(i-1)*10,2]
  }
}

#Plot bias for mu:
plot(plotx_bias[[1]][,1], 
     plotx_bias[[1]][,2], 
     type = "l", 
     col = 1, 
     ylim = c(-0.6,0.6), 
     main = "bias for mu", 
     xlab = "no. of observations",
     ylab = "bias")
for(e in 2:10){
  lines(plotx_bias[[e]][,1], plotx_bias[[e]][,2], type = "l", col = e)
  }
legend("topright",
       legend = c(1:10),
       col = c(1:10),
       lty = 1,
       cex = 0.5)




#Plot bias for sigma:
plot(plotx_bias[[1]][,1], 
     plotx_bias[[1]][,3], 
     type = "l", 
     col = 1, 
     ylim = c(-0.4,0.4), 
     main = "bias for sigma", 
     xlab = "no. of observations",
     ylab = "bias")
for(e in 2:10){
  lines(plotx_bias[[e]][,1], plotx_bias[[e]][,3], type = "l", col = e)
  }
legend("topright",
       legend = c(1:10),
       col = c(1:10),
       lty = 1,
       cex = 0.5)

```


## Grafiken für Emp. StDev.
```{r}
library(ggplot2)

plotx_sd <- vector(mode = "list", length = 10)

for (f in 1:10){
  plotx_sd[[f]] <- matrix(rep(0, 3*5), ncol = 3)
  colnames(plotx_sd[[f]]) <- c("obs", "mu", "sigma")
}

#obs:
for (e in 1:10) {
  for (i in 1:5){
      plotx_sd[[e]][i,1] <- obs[i]
  }
}


#mean:
for (e in 1:10) {
  for (i in 1:5){
      plotx_sd[[e]][i,2] <- empsd_av_result[e +(i-1)*10,1]
  }
}


#sigma:
for (e in 1:10) {
  for (i in 1:5){
      plotx_sd[[e]][i,3] <- empsd_av_result[e +(i-1)*10,2]
  }
}

#Plot bias for mu:
plot(plotx_sd[[1]][,1], 
     plotx_sd[[1]][,2], 
     type = "l", 
     col = 1, 
     ylim = c(0,4), 
     main = "empirical standard deviation for mu", 
     xlab = "no. of observations",
     ylab = "emp. std. dev.")
for(e in 2:10){
  lines(plotx_sd[[e]][,1], plotx_sd[[e]][,2], type = "l", col = e)
  }
legend("topright",
       legend = c(1:10),
       col = c(1:10),
       lty = 1,
       cex = 0.5)




#Plot bias for sigma:
plot(plotx_sd[[1]][,1], 
     plotx_sd[[1]][,3], 
     type = "l", 
     col = 1, 
     ylim = c(0,1.5), 
     main = "empirical standard deviation for sigma", 
     xlab = "no. of observations",
     ylab = "emp. std. dev.")
for(e in 2:10){
  lines(plotx_sd[[e]][,1], plotx_sd[[e]][,3], type = "l", col = e)
  }
legend("topright",
       legend = c(1:10),
       col = c(1:10),
       lty = 1,
       cex = 0.5)

```






## Grafiken für MSE
```{r}
library(ggplot2)

plotx <- vector(mode = "list", length = 10)

for (f in 1:10){
  plotx[[f]] <- matrix(rep(0, 3*5), ncol = 3)
  colnames(plotx[[f]]) <- c("obs", "mu", "sigma")
}

#obs:
for (e in 1:10) {
  for (i in 1:5){
      plotx[[e]][i,1] <- obs[i]
  }
}


#mean:
for (e in 1:10) {
  for (i in 1:5){
      plotx[[e]][i,2] <- MSE_av_result[e +(i-1)*10,1]
  }
}


#sigma:
for (e in 1:10) {
  for (i in 1:5){
      plotx[[e]][i,3] <- MSE_av_result[e +(i-1)*10,2]
  }
}

#Plot MSE for mu:
plot(plotx[[1]][,1], 
     plotx[[1]][,2], 
     type = "l", 
     col = 1, 
     ylim = c(0,0.6), 
     main = "MSE for mu", 
     xlab = "no. of observations",
     ylab = "MSE")
for(e in 2:10){
  lines(plotx[[e]][,1], plotx[[e]][,2], type = "l", col = e)
  }
legend("topright",
       legend = c(1:10),
       col = c(1:10),
       lty = 1,
       cex = 0.5)




#Plot MSE for sigma:
plot(plotx[[1]][,1], 
     plotx[[1]][,3], 
     type = "l", 
     col = 1, 
     ylim = c(0,0.6), 
     main = "MSE for sigma", 
     xlab = "no. of observations",
     ylab = "MSE")
for(e in 2:10){
  lines(plotx[[e]][,1], plotx[[e]][,3], type = "l", col = e)
  }
legend("topright",
       legend = c(1:10),
       col = c(1:10),
       lty = 1,
       cex = 0.5)

```
## Polynome plotten


### function
```{r}
# plot true values
plot_simulation <- function(model = Auswertungsdaten, 
                            data = simulationdata,
                            m, 
                            k, 
                            alpha = 0.05){
  
  data1 <- as.data.frame(simulationdata[[k]][[1]][[m]])

  #fitted model:
  sigma_hat_fitted_min <- model[[m]][[k]][,2] - qnorm(1-alpha/2) * model[[m]][[k]][,4] 
  sigma_hat_fitted_max <- model[[m]][[k]][,2] + qnorm(1-alpha/2) * model[[m]][[k]][,4] 
  

  #true model: 
  sigma_hat_true_min <- model[[m]][[k]][,1] - qnorm(1-alpha/2) * model[[m]][[k]][,3]
  sigma_hat_true_max <- model[[m]][[k]][,1] + qnorm(1-alpha/2) * model[[m]][[k]][,3]

  ggplot(data = data1, 
         aes(x = x, 
             y = y)) +
    theme(text = element_text(size = 40))+
    geom_point(size = 2) + 
    ggtitle(label = "True values (blue) vs. fitted model (red)",
              subtitle = paste0("Polynom ", m , ", Simulation " ,k)) +
    ylab("y") +
    xlab("x") + 
    geom_line(aes(x = x, 
                  y = model[[m]][[k]][,2]), 
              color = 'red', 
              size=2) +
    geom_ribbon(aes(ymin = sigma_hat_fitted_min, 
                    ymax = sigma_hat_fitted_max), 
                alpha = 0.1, 
                color = "red", 
                linetype = 2,
                size = 2,
                fill = "red") + 
    geom_line(aes(x = x, 
                  y = model[[m]][[k]][,1]), 
              color = 'blue', 
              size=2) +
    geom_ribbon(aes(ymin = sigma_hat_true_min, 
                    ymax = sigma_hat_true_max), 
                alpha = 0.1, 
                color = "blue", 
                linetype = 2,
                size = 2, 
                fill = "blue")
}






```

### Plot Generation
```{r}

# Plot separate ggplot figures in a loop.
library(ggplot2)

# Make list of variable names to loop over.



plot_list =  vector(mode = "list", length = 5)
plot_list[[1]] <- vector(mode = "list", length = 50)

for (e in 1:n_sim){

for (i in 1:50) {
  p <- plot_simulation(model = Auswertungsdaten,
                      data = simulationdata,
                      m = i,
                      k = e,
                      alpha = 0.05)
  plot_list[[e]][[i]] = p
}
}


# Save plots to png Makes a separate file for each plot.
for (e in 1:n_sim){
  

for (i in 1:50) {
  file_name = paste("plot_for_simulation_", e, "_polynom_", i, ".png", sep="")
  png(file_name,width=1200,height=800)
  print(plot_list[[e]][[i]])
  dev.off()
}
}


```





